# Generated by Django 2.1.1 on 2018-09-28 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed channel', max_length=127)),
                ('topic', models.CharField(default='[Channel topic]', max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='VerbMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='api.VerbChannel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_posted',),
            },
        ),
        migrations.CreateModel(
            name='VerbServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed server', max_length=100)),
                ('topic', models.CharField(default='[Server topic]', max_length=127)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='verbchannel',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server', to='api.VerbServer'),
        ),
        migrations.AddField(
            model_name='verbchannel',
            name='users',
            field=models.ManyToManyField(related_name='channel_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
